
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test

#
production:
  <<: *default
  database: makertrain_prod
  username: makertr4in
  password: <%= ENV['DB_PASS'] %>
