# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 478d47e71c535991a7730b95de4e32900b5bcaddae9387597052a11b68216ed657871be794d1d78eafe2d9b723d4bcea17ff8638825ba6692adf889923a20ec3

test:
  secret_key_base: d99cf7e450dcc0709e8e423dcf6e946614f7e2ca0be5ac02ea4dc44bd6b3ff434664bef3abd522335807e89cf52c986064aa6280503a06cbddaca2e6a19d0025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
